
const AboutCustomers = () =>{
    return(
        <>
            <h3 className="heading">About Customers</h3>
            <div className="about-section">
                <p>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint exercitationem facere velit explicabo eveniet placeat debitis officia aperiam quasi ratione rerum in voluptatum delectus ut, a mollitia eum sed harum repellendus hic esse rem atque quibusdam obcaecati! Voluptatibus reiciendis tempore accusantium. Perspiciatis at, cum nam in mollitia id, sit minima eveniet voluptatem deserunt itaque modi placeat voluptas harum nemo dolore debitis corporis ipsum aut illo. Itaque suscipit quisquam, doloribus dolor voluptate facere incidunt eligendi repudiandae asperiores a veniam eum sed amet ut velit consequuntur id fugiat et necessitatibus inventore possimus unde pariatur temporibus molestiae. Perspiciatis, impedit! Rem aliquam doloribus fugiat corrupti nobis deserunt inventore, laudantium velit ipsam dolores eaque tenetur atque assumenda recusandae officiis error excepturi sed aspernatur. Ipsum ex pariatur dolores veniam amet laudantium modi nam sequi quas aut quia vero repellendus voluptates animi ipsam earum, blanditiis harum ipsa quibusdam quaerat iste deleniti totam. Explicabo non beatae dolor dolores perferendis voluptate voluptatibus dolore possimus dolorum eius provident nulla, tempore vel animi sequi iste veniam repellendus vero cumque, assumenda temporibus rerum doloremque consequuntur! Suscipit laudantium quos ut, voluptatum quibusdam maiores non eum corporis voluptates vitae tenetur aut fugiat recusandae odio veritatis officiis perspiciatis! Sapiente quos sint, voluptatibus perferendis ratione similique ducimus, eum recusandae tenetur quasi distinctio quia mollitia numquam labore quibusdam laborum. Doloremque harum vero aspernatur fugit nobis perferendis architecto fugiat unde distinctio error, rem quae dolorum mollitia saepe libero soluta veritatis nesciunt ad facere, quasi aliquid, temporibus minus nemo ea. Autem tenetur consectetur minus neque amet, illum recusandae possimus fugit optio nemo ducimus et officiis necessitatibus consequatur sunt. Repellendus, ad. Dolor natus, labore recusandae deleniti iste quidem id, temporibus rerum asperiores nulla aut. Labore reiciendis, iure laboriosam voluptate eaque, voluptates, deleniti aspernatur odit porro optio modi facere consequuntur non sunt atque distinctio mollitia excepturi! Voluptatum animi magni quod maiores?
                </p>
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis repudiandae veritatis eligendi reprehenderit voluptas, neque dolore maxime numquam, quisquam illum inventore doloremque consectetur eaque quaerat? Dolores ipsam nihil, officia incidunt eveniet numquam, natus a assumenda labore cum nostrum, consequuntur voluptatibus aperiam unde excepturi quibusdam tempora. Officiis voluptas nobis vero praesentium expedita fuga incidunt porro et quia blanditiis tempore laboriosam, impedit maiores in veritatis voluptatem, neque, doloremque reprehenderit nisi tempora mollitia. Voluptatibus fugiat architecto quas labore nulla quod aspernatur, nesciunt, animi rem ipsum, cum neque. Vitae laborum corporis minima laboriosam, placeat labore reiciendis neque repudiandae necessitatibus, consequuntur libero aperiam id doloremque. Adipisci ipsa autem consequuntur non illo? Veniam qui provident voluptate eum sit beatae dicta quidem quas eaque enim optio doloremque possimus distinctio earum inventore eligendi totam minus ad, asperiores voluptatum ut architecto. Assumenda placeat aliquam perspiciatis consequuntur recusandae hic corporis. Error atque perspiciatis libero, voluptatibus placeat consequatur ullam! Magni minima ipsum sint quisquam deserunt mollitia alias est iste amet dolore.
                </p>
                <p>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus, blanditiis? Aut fugit iusto, corporis consequatur ipsam eos, quas sunt, porro explicabo error obcaecati facilis velit minus. Quisquam corrupti adipisci dignissimos earum tenetur sequi qui ex suscipit pariatur distinctio cupiditate sint rem possimus architecto omnis dolor ut dolorem at minus, aut fugit perspiciatis molestias. Perspiciatis dolorum laudantium odit provident eligendi debitis minus in voluptates libero esse dolores voluptatum praesentium quidem totam dolore sunt et amet, architecto sapiente natus ex? Adipisci qui sed, deserunt, reiciendis et id, voluptates esse voluptate modi similique blanditiis consequatur accusantium. Vitae nam nulla numquam ratione voluptatem cum fugiat quia error quos eligendi reprehenderit corrupti dolorum at ipsa corporis, illo esse dignissimos, beatae repudiandae. Doloremque laborum unde placeat doloribus, distinctio eos eveniet explicabo voluptate odit cum, similique nam officia delectus. Deserunt quaerat quam nesciunt, suscipit repudiandae earum? Assumenda quo temporibus, fugit iste adipisci odio quod deserunt quae quaerat! Porro aperiam corporis id assumenda est quae itaque odio? Dicta, assumenda asperiores itaque vel ea repellendus est ratione? Quae repellat ea dicta atque laboriosam minima, voluptas, id, nesciunt voluptate numquam maxime incidunt iusto officia doloremque necessitatibus amet sunt sequi. Adipisci aliquam voluptatum nulla nisi distinctio. Quidem dicta tempora eaque omnis?
                </p>
            </div>
        </>
    )
}
export default AboutCustomers;