
const AboutCompany = () =>{
    return(
        <>
            <h3 className="heading">About Company</h3>
            <div className="about-section">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur veniam nisi repudiandae eos asperiores vitae dolorem repellendus facilis ea odio voluptates, repellat exercitationem modi beatae ut minus ipsa molestias mollitia pariatur eum nihil quis. Dicta assumenda et, corporis repudiandae inventore neque non accusantium itaque praesentium, ipsa tenetur, debitis sapiente doloremque placeat iste veritatis explicabo dolorem enim fugit sit. Et ducimus nihil blanditiis! Officia, inventore dignissimos impedit porro facilis hic facere nulla qui, possimus voluptatibus quibusdam perferendis quasi in, et rem iusto esse eaque doloribus natus doloremque aliquid a reiciendis? Voluptate unde porro, expedita beatae delectus odit exercitationem quas accusamus minus, vero cupiditate veniam doloremque numquam neque asperiores? Ut voluptatum excepturi culpa iste suscipit incidunt ratione magnam, numquam facere ad optio vel, deserunt voluptate officia eos voluptas non eveniet consequatur laboriosam necessitatibus amet nihil provident asperiores? Pariatur incidunt voluptatum reiciendis! Iusto, nesciunt odio doloribus dolore officiis animi ipsum dolorem id consectetur unde ex tenetur eos in? Tempore ratione exercitationem officiis dolorem eveniet adipisci, expedita voluptatibus dolorum. Tempora debitis quia sed voluptas accusantium accusamus sequi amet, voluptate harum reprehenderit obcaecati quo doloremque voluptatibus aliquid veniam. Recusandae, maiores facere. Amet quam quas odit atque, facere dolor nulla, illum sequi, recusandae repellendus incidunt dolorum aliquid totam nam soluta beatae minus exercitationem maxime ad debitis eum. Quam accusamus inventore, id sed sit provident voluptatum dolorum dolor beatae quia aliquam quas! Facere, maiores. Facilis earum inventore tempore mollitia! Quam sequi provident deserunt numquam est ea illum mollitia officia cumque, corporis tempore cupiditate ratione ut tempora asperiores?
                </p>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt nobis dignissimos illum temporibus officia fugiat officiis itaque maiores nostrum maxime, iusto quo pariatur nam sapiente quasi. Quia corrupti commodi excepturi nisi, porro libero dolore sit veniam itaque quibusdam quasi eos, fugiat mollitia, harum quas quam exercitationem delectus. Praesentium dolorem dolorum aliquam dolor dignissimos deserunt nihil perferendis quo debitis blanditiis saepe illum, numquam iusto architecto, optio placeat modi explicabo corrupti. Cumque, ipsum vero, dolorum totam, rem dolores minima sint provident quo ipsa laboriosam officia quas voluptates dicta repellendus reiciendis numquam ut temporibus asperiores explicabo quaerat consequuntur! Rerum dolorem ipsum sapiente pariatur culpa labore asperiores odio repellat assumenda error sequi, fugit cum quod laborum distinctio ab doloribus facilis maxime, unde harum quas reiciendis. Itaque fugiat accusantium esse dolores, voluptatem fuga dolorum aperiam!
                </p>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque perferendis iste cumque, ex explicabo velit dolor. Accusamus aperiam perferendis possimus quaerat quam culpa voluptas nulla consequuntur fugit alias inventore repudiandae, velit natus molestiae in qui facilis voluptates soluta harum rerum reprehenderit voluptatum! Hic asperiores animi in, illum ea alias! Itaque eos architecto, repellendus, distinctio omnis facere ducimus tenetur repellat, aliquam ea corrupti voluptatum eveniet porro ab ipsam pariatur? Fugit aliquid tenetur modi obcaecati earum? Consequuntur sunt omnis non, est odit atque quas aspernatur reprehenderit repellat natus fuga a dicta illum fugiat magnam minus aut. Dolor, esse voluptates. Adipisci qui totam rem error, doloremque ducimus ratione! Nostrum eum excepturi voluptatum ipsa esse eius, quidem fuga, error quaerat illo velit voluptas quasi placeat sit facere reiciendis in vitae? Ullam numquam a laboriosam vitae voluptas molestiae, accusantium tempore iste alias enim ad! Excepturi ipsum similique odio est, maxime eveniet harum quis ea veritatis autem nostrum soluta laborum perspiciatis, quibusdam eius cupiditate dolorem labore nisi iste nesciunt! Tempora nihil nisi corrupti similique odio, numquam consequatur est enim quae. Harum odit quibusdam quia nobis cum!
                </p>
            </div>
        </>
    )
}
export default AboutCompany;